/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "Join the Discord!": "加入 Discord!",
    "Activities": "活动",
    "Close": "关闭",
    "Got it!": "知道了！",
    "Electro Shards:": "电子碎片：",
    "Help & Settings": "帮助 & 设置",
    "Electronics Clicker": "电子点击器",
    "News": "新闻",
    "Previous": "上一个",
    "Next": "下一个",
    "Money:": "金钱:",
    "Junktown Nexus": "旧城枢纽",
    "Join our Discord community to share feedback and suggestions!": "加入我们的Discord社区来分享反馈和建议吧！",
    "Notifications": "通知",
    "Open Credit Store": "打开信用商店",
    "Open Crafting Menu": "打开制作菜单",
    "Open Skills Center": "打开技能中心",
    "Open Automation Center": "打开自动化中心",
    "Open Junk Store": "打开旧货商店",
    "Credit Store": "信用商店",
    "Crafting Menu": "制作菜单",
    "Skills Center": "技能中心",
    "Automation Center": "自动化中心",
    "Junk Store": "旧货商店",
    "Quest Log": "任务日志",
    "Progress": "进度",
    "Show More": "显示更多",
    "Slot Machine": "自动售货机",
    "Click on the junk pile to collect some scrap": "点击垃圾堆收集一些废料",
    "The Scraptagon 🔒": "",
    "Trash Clicker": "垃圾点击器",
    "What's New:": "新内容:",
    "Check the Changelog for more Information or join the Discord!": "查看更新日志获取更多信息或加入Discord！",
    "Click the junk, kid. Scrap doesn't collect itself.": "点击垃圾，孩子。废料不会自己收集起来。",
    "Do you love playing in the trash?": "你喜欢在垃圾堆里玩吗？",
    "Game Tips": "游戏提示",
    "Join Discord": "加入 Discord",
    "Junk:": "垃圾:",
    "Junk/sec:": "垃圾/秒:",
    "Open Electro Store": "打开电子商店",
    "✨ Tons of Bugfixes": "✨ 大量的bug修复",
    "✨ Tons of System Reworks": "✨ 大量的系统重做",
    "🔧 A tiny bit of new content": "🔧 一点点的新内容",
    "Show Less": "显示更少",
    "First Steps": "第一步",
    "Begin Crafting": "开始制作",
    "Early Progression": "早期进度",
    "Passive Income": "被动收入",
    "In unrelated news, the vending machine is humming ominously again.": "另一条不相关的新闻是，自动售货机又开始发出不祥的嗡嗡声了。",
    "Pizza delivery drones under fire for 'accidental' toppings": "送披萨的无人机因“意外”配料而遭到抨击",
    "Reminder: Do not lick the glowing circuits. Again.": "提醒：不要舔发光电路。再一次。",
    "Rumor: A scrap trader found a functioning toaster. Experts remain skeptical.": "谣言：一个废品商人发现了一个能用的烤面包机。专家们仍持怀疑态度。",
    "Streetrat spotted stealing capacitors again. Local bots unimpressed.": "街上又发现偷电容器了。本地机器人对此无动于衷。",
    "That's the spirit. Go hit the Store. Buy somethin' useful for once.": "就是这种精神。去商店看看吧。买一些有用的东西。",
    "Trash surge insurance now available. Terms may apply.": "垃圾激增保险现在可用。条款可以申请。",
    "Virtual cat cafes explode in popularity": "虚拟猫咪咖啡馆大受欢迎",
    "Visit the store and buy your first upgrade": "访问商店，购买你的第一个升级",
    "You have no one that loves you in this world": "你在这个世界上没有一个爱你的人",
    "Junk)": "垃圾)",
    "Owned:": "拥有:",
    "Show Notifications": "显示通知",
    "+2 Automatic Clicks per second (Consumes 1 Auto Clicker Bot)": "+2自动点击每秒（消耗1自动点击机器人）",
    "+1 Automatic Click per second (generates Junk automatically as if clicked by the player)": "+1自动点击每秒（自动生成垃圾，如果玩家点击）",
    "s remaining)": " 剩余)",
    "⚡ TRASH SURGE ACTIVE! (": "⚡ 垃圾激增活跃!（",
    "⋯ In Progress": "⋯ 进行中",
    "⏛ What Are Capacitors?": "⏛ 什么是电容器？",
    "🔌 Tronics Clicker": "🔌 电子点击器",
    "Click Enhancer": "点击强化器",
    "⚡ TRASH SURGE ACTIVE! (": "⚡垃圾激增！（",
    "⚡ TRASH SURGE: Junk overflow detected — grab it while it lasts!": "⚡垃圾激增：垃圾溢出检测-抓住它，而它持续！",
    "⚡ What Are Electro Shards?": "⚡什么是电子碎片？",
    "✨ What Is The Flying Crystal?": "✨飞行水晶是什么?",
    "💡 Tip: Appears once every 30 minutes.": "💡提示：每30分钟出现一次。",
    "💡 Tip: Keep an eye on rare pickups — they matter more than you think.": "💡提示：关注那些稀有的拾取物品——它们比你想象的更重要。",
    "💡 Tip: Keep an eye on rare pickups and hidden quest rewards — they matter more than you think.": "💡提示：关注稀有拾取物品和隐藏任务奖励——它们比你想象的更重要。",
    "💡 Tip: Time your prestige carefully - make sure you've maximized your current run's potential first!": "💡提示：仔细安排你的声望-确保你已经最大化了你当前跑步的潜力！",
    "💡 Tip: Unlock the First Node or you WILL be STUCK.": "💡提示：解锁第一个节点，否则你将被卡住。",
    "💡 Unlocks new tech, ElectroShop items, and advanced systems post-prestige": "💡解锁新技术，电子商店项目，和先进的系统后声望",
    "💡 What Is The Tech Tree?": "💡什么是科技树？",
    "📈 Benefits from Tronics per Click upgrades": "📈受益于Tronics每次点击升级",
    "🔁 How Prestige Works": "🔁威望如何运作",
    "🔌 Generates 1 Tronic per click": "🔌每次点击产生1 Tronic",
    "A glorified toaster tuned to the shard frequency. Hums when it works.": "一个调谐到碎片频率的烤面包机。工作时发出嗡嗡声。",
    "A massive holographic display that attracts more scrappers to your territory": "一个巨大的全息显示器，吸引更多的拳击手到你的领土",
    "A mysterious figure was seen whispering to a pile of wires.": "有人看见一个神秘的人影对着一堆电线耳语。",
    "A sturdy bag that helps you collect more junk with each click": "一个坚固的袋子，帮助你收集更多的垃圾与每点击",
    "Accumulate 10,000 Junk": "堆积1万件垃圾",
    "Ask about crystal shards": "询问水晶碎片",
    "Automated system that processes urban waste into valuable junk": "将城市垃圾加工成有价值的垃圾的自动化系统",
    "Autonomous drone that scans the area for valuable junk": "自动无人机扫描该区域寻找有价值的垃圾",
    "Average JPS:": "平均译本:",
    "Badges": "徽章",
    "Can be rarely found during normal Surges and more commonly in Tronics Surges.": "在正常浪涌中很少发现，而在电子浪涌中更常见。",
    "Channel unstable energy into the system — one click at a time.": "通道不稳定的能量进入系统-点击一次。",
    "Circuit Pulse Mastery": "电路脉冲掌握",
    "Click Upgrades": "点击升级",
    "Cogfather: If it's buzzing, it's working. If it's sparking, it's improving.": "教父：如果它嗡嗡作响，它就在工作。如果它有火花，它就在改善。",
    "Cogfather's First Secret": "教父的第一个秘密",
    "Cogfather's Tip: If it's buzzing, it's working. If it's sparking, it's improving.": "教父的建议：如果它嗡嗡作响，它就在工作。如果它有火花，它就在改善。",
    "Collect 1,000 Junk": "收集1000个垃圾",
    "Collect 10 Electro Shards": "收集10个电子碎片",
    "Collect 5 Electro Shards": "收集5个电子碎片",
    "Collect it before it vanishes to gain 1 Electro Shard.": "在它消失之前收集它可以获得1个电子碎片。",
    "Collect special resources": "收集特殊资源",
    "Complete the Ascension Questline": "完成扬升任务线",
    "Cosmetic Badge": "化妆品的徽章",
    "Craft special quest items (like the Prestige Crystal)": "制作特殊任务道具（如威望水晶）",
    "Craft the Prestige Crystal": "制作威望水晶",
    "Crystal Time Reduction:": "晶体时间减少：",
    "Cybernetic finger enhancements for maximum clicking efficiency": "控制手指增强最大的点击效率",
    "Don't forget to oil your clicker. Rust is a liar.": "别忘了给遥控器上油。生锈是一个骗子。",
    "Electro Shard Milestones": "电子碎片里程碑",
    "Electro Shards are a rare, high-tier resource used to power advanced systems. They are primarily required to:": "电子碎片是一种稀有的高级资源，用于为高级系统提供动力。他们主要需要：",
    "Electro Shards can be acquired through:": "电子碎片可以通过以下方式获得：",
    "Electromagnetic device that attracts valuable junk automatically": "自动吸引贵重垃圾的电磁装置",
    "Electroshard miner v0.1 (Premium Junk Upgrade)": "电碎片矿工v0.1（高级垃圾升级）",
    "Enable HoloBillboard": "启用全息广告牌",
    "Ever felt the hum of the city? There's power in the ether, waiting to be harnessed.": "感受过城市的喧嚣吗？以太中有力量，等着被利用。",
    "First Ascension": "第一次提升",
    "Global JPS Multiplier:": "全局JPS倍增器：",
    "Greasy Milestone": "油腻的里程碑",
    "Hide": "隐藏",
    "Hire a local to automatically collect junk for you": "雇一个当地人帮你自动收集垃圾",
    "Holo Billboard": "整体的广告牌",
    "How to Unlock Prestige:": "如何解锁声望：",
    "How's business?": "业务怎么样?",
    "Junk +": "垃圾+",
    "Junk futures hit an all-time high — economists baffled.": "垃圾期货创下历史新高，经济学家们感到困惑。",
    "Junk Magnet": "垃圾磁铁",
    "Junk Slots": "垃圾槽",
    "Junkie Starter": "迷起动器",
    "Keep collecting and upgrading your tools": "继续收集和升级你的工具",
    "Large capacity cart that greatly increases automatic collection": "大容量推车，大大增加自动收集",
    "Local helper union demands one less bolt per day.": "当地帮工工会要求每天减少一个螺栓。",
    "m": "米",
    "Max Click Enhancers": "最大点击增强器",
    "Max Visible Drones": "最大可见无人机",
    "Most inventory items and crafting materials": "大多数库存物品和制作材料",
    "New study finds clicking improves morale. Source: the clicker industry.": "新研究发现，点击可以提高士气。来源：点击器行业。",
    "Next surge in:": "下一个激增：",
    "Now you're hoarding like a real scavver.": "现在你像个真正的拾荒者一样囤东西了。",
    "Passive Upgrades": "被动的升级",
    "Passively generates 1 Electro Shard every 30 minutes, up to a max of 3 stored.": "被动地每30分钟产生1个电子碎片，最多可储存3个。",
    "Power outage in Sector 3 traced back to an overclocked potato battery.": "第三区停电是因为土豆电池超频。",
    "Pre-Prestige": "前声望",
    "Premium": "溢价",
    "Premium Items": "高端项目",
    "Prestige-exclusive upgrades and bonuses": "声望专属升级和奖励",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "s": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",
    'Twitter': 'Twitter',
    "Discord": "Discord",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "gityxcom": "gityxcom",
    "Footer": "Footer",
    "Wiki": "Wiki",
    "gityx": "gityx",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'II',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    'Jan': '1月',
    'Feb': '2月',
    'Mar': '3月',
    'Apr': '4月',
    'May': '5月',
    'Jun': '6月',
    'Jul': '7月',
    'Aug': '8月',
    'Sep': '9月',
    'Oct': '10月',
    'Nov': '11月',
    'Dec': '12月',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": " ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "Task: ": "任务: ",
    "The Scraptagon": "废料",
    "🎮 New Version Available: ": "🎮 新版本可用: ",
    "Quest Completed: ": "任务已完成: ",
    "Auto Clicker Bot": "自动点击机器人",
    "💡 Tip: ": "💡 提示: ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    ' I': ' I',
    ' II': ' II',
    ' III': ' III',
    ' IV': ' IV',
    ' V': ' V',
    ' VI': ' VI',
    ' VII': ' VII',
    ' VIII': ' VIII',
    ' X': ' X',
    ' XI': ' XI',
    ' XII': ' XII',
    ' XIII': ' XIII',
    ' XIV': ' XIV',
    ' XV': ' XV',
    ' XVI': ' XVI',
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)h$/,
    /^([\d\.]+)m$/,
    /^([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^v([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+) Sp$/,
    /^([\d\.]+) Oc$/,
    /^([\d\.]+) Dc$/,
    /^([\d\.]+) UDc$/,
    /^([\d\.]+) No$/,
    /^([\d\.]+) Sx$/,
    /^([\d\.]+) QaDc$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])|[\u21A9\u21AA\u25B6\u25C0\u2B06\u2B07\u2B05\u2B95\u2B99\u2B9A]+$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])+$/,
    // /^[\uD800-\uFFFF]+$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//字母加数字：([\d\.]+[A-Za-z])
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
//&nbsp;空格：\xA0
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Collected (.+) bonus junk!$/, '收集 $1 奖励垃圾！'],
    [/^Click (.+) times$/, '点击 $1 次'],
    [/^Jan ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 1 月 $1, $3:$4'],
    [/^Feb ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 2 月 $1, $3:$4'],
    [/^Mar ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 3 月 $1, $3:$4'],
    [/^Apr ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 4 月 $1, $3:$4'],
    [/^May ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 5 月 $1, $3:$4'],
    [/^Jun ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 6 月 $1, $3:$4'],
    [/^Jul ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 7 月 $1, $3:$4'],
    [/^Aug ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 8 月 $1, $3:$4'],
    [/^Sep ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 9 月 $1, $3:$4'],
    [/^Oct ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 10 月 $1, $3:$4'],
    [/^Nov ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 11 月 $1, $3:$4'],
    [/^Dec ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 12 月 $1, $3:$4'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^\+([\d\.]+)\% Click Power$/, '\+$1\% 点击力量'],
    [/^\+([\d\.]+)\% global JPS$/, '\+$1\% 全局 垃圾每秒（JPS）'],
    [/^\+([\d\.]+)\% global Junk\/sec boost$/, '\+$1\% 全局 垃圾每秒 提升'],
    [/^\+([\d\.]+)\% JPS \(([\d\.,]+)s\)$/, '\+$1\% 垃圾每秒（JPS）($2 秒)'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^\+([\d\.,]+) Auto Click\/sec$/, '\+$1 自动点击/秒'],
    [/^\+([\d\.,]+) Junk$/, '\+$1 垃圾'],
    [/^\+([\d\.,]+) Junk\/Click, (.+) Cost$/, '\+$1 垃圾/点击, $2 成本'],
    [/^\+([\d\.,]+) Junk\/sec, (.+) Cost$/, '\+$1 垃圾/秒, $2 成本'],
    [/^([\d\.,]+)x Electro Shard$/, '$1x 电子碎片'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^level ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^level: ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);